FROM python:3.12.0
# Set the working directory
WORKDIR /api

# Copy the current directory contents into the container
COPY .. /api

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8080
EXPOSE 8080

# Define environment variable
ENV FLASK_APP=main.py

# Run the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]